version: "3.9"
services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"   # Oracle listener
      - "5500:5500"   # EM Express (optional)
    environment:
      ORACLE_PASSWORD: ${ORACLE_PWD:-oracle}
      APP_USER: ${ORACLE_APP_USER:-APPUSER}
      APP_USER_PASSWORD: ${ORACLE_APP_PWD:-apppwd}
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./oracle/schema:/opt/sql          # mount your DDL for easy runs
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM dual;' | sqlplus -s SYSTEM/${ORACLE_PWD:-oracle}@localhost:1521/XEPDB1 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 20
    restart: unless-stopped

volumes:
  oracle-data:
